/*
 * File: app/view/NoConnectionPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.NoConnectionPanel', {
    extend: 'Ext.Panel',

    config: {
        items: [
            {
                xtype: 'container',
                centered: true,
                items: [
                    {
                        xtype: 'label',
                        height: 126,
                        html: 'No internet connection available.<br/><br/> Please check your internet connection.',
                        ui: 'light',
                        width: 321
                    },
                    {
                        xtype: 'button',
                        itemId: 'mybutton1',
                        text: 'Try Again'
                    }
                ]
            }
        ],
        listeners: [
            {
                fn: 'onMybutton1Tap',
                event: 'tap',
                delegate: '#mybutton1'
            }
        ]
    },

    onMybutton1Tap: function(button, e, options) {
        window.open('app.html');
    }

});